### ISSUE TITLE
Running MotionMapper for multiple DLC csvs and mapping onto same behavioral space

### ISSUE THREAD

**Issue by annieandbrianneedacode** [DeepLabCut/DLCutils#11]
Hi,

I just had two questions: (1) Can I use motionmapper to map multiple csvs from DLC to one single postural map? Do I just put in multiple file names into deeplabcut_into_motionMapper.m for the variable deeplabcutfile (e.g. deeplabcutfile = 'data1.csv','data2.csv')? Will this do what I described above? 

(2) How do I map one dataset's postural time series data onto another dataset's? This was done in the original paper (section 4.4 of Berman et al.) for male and female flies. 

Thanks,
Annie

**Comment by AlexEMG** [comment]
I think this question should be posted on the https://github.com/gordonberman/MotionMapper github!
