### ISSUE TITLE
Need help with code 

### ISSUE THREAD

**Issue by Neurosci128** [DeepLabCut/DLCutils#15]
Hello! I've been following the code, step by step, and it has been working up to this point:

![image](https://user-images.githubusercontent.com/73357455/102702716-4f83d980-422b-11eb-8498-c1cbf8ca180b.png)

After that, I didn't see anything (X or Y coordinates or anything related to the video)? What should I be doing now?

**Comment by AlexEMG** [comment]
Not clear what you try to do with your code. For loading and plotting just follow this example notebook: 

https://github.com/DeepLabCut/DLCutils/blob/master/Demo_loadandanalyzeDLCdata.ipynb

(and exchange the filename).
