### ISSUE TITLE
DLC to motionmapper : Error Using scatter - CDatat must be an RGB triplet

### ISSUE THREAD

**Issue by tochenan** [DeepLabCut/DLCutils#7]
Hello, 
I am trying to use the deeplabcut_into_motionMapper.m function but got the following error:

Mean value of sigma: 0.010111
Minimum value of sigma: 0.0022873
Maximum value of sigma: 0.087411
Iteration 1: error is 99.4207, change is 1
Error using scatter (line 110)
CData must be an RGB triplet, an M-by-1 vector of the same length as X, or an M-by-3 matrix.

Error in tsne_p_sparse (line 149)
                    scatter(ydata(:,1),ydata(:,2),[],parameters.signalLabels,'filled')

Error in tsne_d (line 60)
        [yData,errors] = tsne_p_sparse(P, parameters, no_dims, relTol);

Error in run_tSne (line 39)
    [yData,betas,P,errors] = tsne_d(D,parameters);

Error in deeplabcut_into_motionMapper (line 106)
[embeddingValues{i},~] = run_tSne(BRAC36002e,parameters);

any idea about why this happened?

**Comment by AlexEMG** [comment]
Seems like the colormap has a different format.

**Comment by annieandbrianneedacode** [comment]
Hi I'm having the same issue and wondering how to fix this? I can't find which .m file the colormap originates from.

**Comment by AlexEMG** [comment]
I just added the colormap from Gordon: https://github.com/AlexEMG/DLCutils/commit/213664d8dadfcecc23a7243aabef8f61bada9d39

**Comment by MMathisLab** [comment]
This is not the issue, as I already had that in my repo, which I suggest using as it has several pieces of missing code already: https://github.com/MMathisLab/MotionMapper/blob/master/utilities/saved_colormaps.mat

**Comment by liamwilt** [comment]
Hi, I am experiencing the same issue and I attempted to use DLC to motionmapper today with the colormap intact. I know that isn't the issue, but do we know what might be causing the error?

`Error using scatter (line 110)
CData must be an RGB triplet, an M-by-1 vector of the same length as X, or an M-by-3 matrix.

Error in tsne_p_sparse (line 149)
                    scatter(ydata(:,1),ydata(:,2),[],parameters.signalLabels,'filled')

Error in tsne_d (line 60)
        [yData,errors] = tsne_p_sparse(P, parameters, no_dims, relTol);

Error in run_tSne (line 39)
    [yData,betas,P,errors] = tsne_d(D,parameters);

Error in deeplabcut_into_motionMapper (line 118)
[embeddingValues{i},~] = run_tSne(data,parameters);`

**Comment by annieandbrianneedacode** [comment]
I am still having this issue and have downloaded all of the missing code that MMathisLab had supplied. 

Error below: 
Error using scatter (line 110)
CData must be an RGB triplet, an M-by-1 vector of the same length as X, or an M-by-3 matrix.

Error in tsne_p_sparse (line 149)
                    scatter(ydata(:,1),ydata(:,2),[],parameters.signalLabels,'filled')

Error in tsne_d (line 60)
        [yData,errors] = tsne_p_sparse(P, parameters, no_dims, relTol);

Error in run_tSne (line 39)
    [yData,betas,P,errors] = tsne_d(D,parameters);

Error in deeplabcut_into_motionMapper (line 118)
[embeddingValues{i},~] = run_tSne(data,parameters);

**Comment by annieandbrianneedacode** [comment]
When I change line 103-105 in deeplabcut_into_motionmapper.m to 
trainingSetData = data(1:end,:);
trainingAmps = amps(1:end);
parameters.signalLabels = log10(trainingAmps);

before it was using a skiplength of 5 (from line 98) 
skipLength = round(length(data(:,1))/parameters.trainingSetSize);
if skipLength < 5
    skipLength = 5;
end

I got it to run but am not sure if this will affect the way this data is plotted?

**Comment by AlexEMG** [comment]
Gordon says: "This is likely due to the fact that the saved_colormaps.mat has not been loaded into the workspace"

**Comment by annieandbrianneedacode** [comment]
saved_colormaps.mat is loaded and I still have this issue. I fixed it with I wrote above by changing the trainingsetdata and trainingamps.

**Comment by liamwilt** [comment]
I will give this a shot. Thank you, @annieandbrianneedacode. Regarding your concern though - " got it to run but am not sure if this will affect the way this data is plotted?" - do you know if the data plots were affected by your modified code yet? Thank you for your help!
